=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/subtransaction/SubTransactionTest/subtransaction.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--Root element-->
<!ELEMENT statements (subtransBegin | subtransEnd | subtransRollback | savepoint | rollbackTo | releaseSavepoint)*>

<!--different statements-->

<!ELEMENT subtransBegin (delete)* >
<!ATTLIST subtransBegin error CDATA #IMPLIED >

<!ELEMENT subtransEnd (delete)* >
<!ATTLIST subtransEnd error CDATA #IMPLIED >

<!ELEMENT subtransRollback (delete)* >
<!ATTLIST subtransRollback error CDATA #IMPLIED >

<!ELEMENT savepoint (delete)* >
<!ATTLIST savepoint error CDATA #IMPLIED 
                    name  CDATA #REQUIRED >

<!ELEMENT rollbackTo (delete)* >
<!ATTLIST rollbackTo error CDATA #IMPLIED 
                     name  CDATA #REQUIRED >

<!ELEMENT releaseSavepoint (delete)* >
<!ATTLIST releaseSavepoint error CDATA #IMPLIED 
                           name  CDATA #REQUIRED >


<!ELEMENT delete EMPTY>
<!ATTLIST delete insertOfStatement CDATA #REQUIRED >

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/subtransaction/SubTransactionTest/a4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "subtransaction.dtd">
<statements>

	<savepoint name="prog1"/>
	<savepoint name="prog2"/>

	<rollbackTo name="prog1"/>
	<rollbackTo name="prog1"/>
	<releaseSavepoint name="prog1"/>

	<subtransBegin/>
	<rollbackTo name="prog2">
		<delete insertOfStatement="4"/>
		<delete insertOfStatement="5"/>
	</rollbackTo>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/subtransaction/SubTransactionTest/a5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "subtransaction.dtd">
<statements>

	<subtransBegin/>

		<savepoint name="u1_prog1"/>

			<subtransBegin/>
			<subtransEnd/>

			<subtransBegin/>
			<subtransRollback/>

			<subtransBegin/>
			<subtransRollback/>

		<releaseSavepoint name="u1_prog1"/>

		<savepoint name="u2_prog1"/>

			<subtransBegin/>
			<subtransBegin/>
			<subtransBegin/>

			<subtransEnd/>
			<subtransRollback/>
			<subtransEnd/>

		<releaseSavepoint name="u2_prog1"/>

		<savepoint name="u3_prog1"/>

			<subtransBegin/>
			<subtransEnd/>

			<subtransBegin/>
			<subtransBegin/>

			<subtransRollback/>
			<subtransEnd/>

		<rollbackTo name="u3_prog1"/>


	<subtransEnd/>

	<savepoint name="prog2"/>

		<subtransBegin>
			<delete insertOfStatement="0"/>
			<delete insertOfStatement="3"/>
			<delete insertOfStatement="6"/>
			<delete insertOfStatement="9"/>
		</subtransBegin>

		<subtransEnd>
			<delete insertOfStatement="12"/>
			<delete insertOfStatement="15"/>
			<delete insertOfStatement="18"/>
			<delete insertOfStatement="21"/>
		</subtransEnd>

		<subtransBegin>
			<delete insertOfStatement="1"/>
			<delete insertOfStatement="4"/>
			<delete insertOfStatement="7"/>
			<delete insertOfStatement="10"/>
		</subtransBegin>

		<subtransRollback>
			<delete insertOfStatement="13"/>
			<delete insertOfStatement="16"/>
			<delete insertOfStatement="19"/>
			<delete insertOfStatement="22"/>
		</subtransRollback>

		<subtransBegin>
			<delete insertOfStatement="2"/>
			<delete insertOfStatement="5"/>
			<delete insertOfStatement="8"/>
			<delete insertOfStatement="11"/>
		</subtransBegin>

		<subtransRollback>
			<delete insertOfStatement="14"/>
			<delete insertOfStatement="17"/>
			<delete insertOfStatement="20"/>
			<delete insertOfStatement="23"/>
		</subtransRollback>

	<rollbackTo name="prog2"/>


	<subtransBegin/>

		<savepoint name="u1_prog3"/>
		<savepoint name="u2_prog3"/>
		<savepoint name="u3_prog3"/>

		<releaseSavepoint name="u3_prog3"/>
		<rollbackTo name="u1_prog3"/>
		<releaseSavepoint name="u1_prog3"/>
		<rollbackTo name="u2_prog3"/>



		<savepoint name="u4_prog3">
			<delete insertOfStatement="35"/>
		</savepoint>

		<savepoint name="u5_prog3">
			<delete insertOfStatement="36"/>
		</savepoint>

		<savepoint name="u6_prog3">
			<delete insertOfStatement="37"/>
		</savepoint>

		<releaseSavepoint name="u4_prog3">
			<delete insertOfStatement="38"/>
		</releaseSavepoint>

		<rollbackTo name="u5_prog3">
			<delete insertOfStatement="39"/>
		</rollbackTo>

		<releaseSavepoint name="u6_prog3">
			<delete insertOfStatement="40"/>
		</releaseSavepoint>


	<subtransRollback/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/subtransaction/SubTransactionTest/test22.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "subtransaction.dtd">
<statements>
	<savepoint name="start0"/>
	<savepoint name="start1"/>
	<savepoint name="start2"/>
	<savepoint name="start3"/>
	<savepoint name="start4"/>
	<savepoint name="start5"/>
	<savepoint name="start6"/>
	<savepoint name="start7"/>
	<savepoint name="start8"/>
	<savepoint name="start9"/>

	<savepoint name="start10"/>
	<savepoint name="start11"/>
	<savepoint name="start12"/>
	<savepoint name="start13"/>
	<savepoint name="start14"/>
	<savepoint name="start15"/>
	<savepoint name="start16"/>
	<savepoint name="start17"/>
	<savepoint name="start18"/>
	<savepoint name="start19"/>

	<savepoint name="start20"/>
	<savepoint name="start21"/>
	<savepoint name="start22"/>
	<savepoint name="start23"/>
	<savepoint name="start24"/>
	<savepoint name="start25"/>
	<savepoint name="start26"/>
	<savepoint name="start27"/>
	<savepoint name="start28"/>
	<savepoint name="start29"/>

	<savepoint name="start30"/>
	<savepoint name="start31"/>
	<savepoint name="start32"/>
	<savepoint name="start33"/>
	<savepoint name="start34"/>
	<savepoint name="start35"/>
	<savepoint name="start36"/>
	<savepoint name="start37"/>
	<savepoint name="start38"/>
	<savepoint name="start39"/>

	<savepoint name="start40"/>
	<savepoint name="start41"/>
	<savepoint name="start42"/>
	<savepoint name="start43"/>
	<savepoint name="start44"/>
	<savepoint name="start45"/>
	<savepoint name="start46"/>
	<savepoint name="start47"/>
	<savepoint name="start48"/>
	<savepoint name="start49"/>

	<savepoint name="start50"/>
	<savepoint name="start51"/>
	<savepoint name="start52"/>
	<savepoint name="start53"/>
	<savepoint name="start54"/>
	<savepoint name="start55"/>
	<savepoint name="start56"/>
	<savepoint name="start57"/>
	<savepoint name="start58"/>
	<savepoint name="start59"/>



	<rollbackTo name="start59"/>
	<rollbackTo name="start58"/>
	<rollbackTo name="start57"/>
	<rollbackTo name="start56"/>
	<rollbackTo name="start55"/>
	<rollbackTo name="start54"/>
	<rollbackTo name="start53"/>
	<rollbackTo name="start52"/>
	<rollbackTo name="start51"/>
	<rollbackTo name="start50"/>

	<rollbackTo name="start49"/>
	<rollbackTo name="start48"/>
	<rollbackTo name="start47"/>
	<rollbackTo name="start46"/>
	<rollbackTo name="start45"/>
	<rollbackTo name="start44"/>
	<rollbackTo name="start43"/>
	<rollbackTo name="start42"/>
	<rollbackTo name="start41"/>
	<rollbackTo name="start40"/>

	<rollbackTo name="start39"/>
	<rollbackTo name="start38"/>
	<rollbackTo name="start37"/>
	<rollbackTo name="start36"/>
	<rollbackTo name="start35"/>
	<rollbackTo name="start34"/>
	<rollbackTo name="start33"/>
	<rollbackTo name="start32"/>
	<rollbackTo name="start31"/>
	<rollbackTo name="start30"/>

	<rollbackTo name="start29"/>
	<rollbackTo name="start28"/>
	<rollbackTo name="start27"/>
	<rollbackTo name="start26"/>
	<rollbackTo name="start25"/>
	<rollbackTo name="start24"/>
	<rollbackTo name="start23"/>
	<rollbackTo name="start22"/>
	<rollbackTo name="start21"/>
	<rollbackTo name="start20"/>

	<rollbackTo name="start19"/>
	<rollbackTo name="start18"/>
	<rollbackTo name="start17"/>
	<rollbackTo name="start16"/>
	<rollbackTo name="start15"/>
	<rollbackTo name="start14"/>
	<rollbackTo name="start13"/>
	<rollbackTo name="start12"/>
	<rollbackTo name="start11"/>
	<rollbackTo name="start10"/>

	<rollbackTo name="start9"/>
	<rollbackTo name="start8"/>
	<rollbackTo name="start7"/>
	<rollbackTo name="start6"/>
	<rollbackTo name="start5"/>
	<rollbackTo name="start4"/>
	<rollbackTo name="start3"/>
	<rollbackTo name="start2"/>
	<rollbackTo name="start1"/>
	<rollbackTo name="start0"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/subtransaction/SubTransactionTest/test23.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "subtransaction.dtd">
<statements>
	<savepoint name="start0"/>
	<savepoint name="start1"/>
	<savepoint name="start2"/>
	<savepoint name="start3"/>
	<savepoint name="start4"/>
	<savepoint name="start5"/>
	<savepoint name="start6"/>
	<savepoint name="start7"/>
	<savepoint name="start8"/>
	<savepoint name="start9"/>

	<savepoint name="start10"/>
	<savepoint name="start11"/>
	<savepoint name="start12"/>
	<savepoint name="start13"/>
	<savepoint name="start14"/>
	<savepoint name="start15"/>
	<savepoint name="start16"/>
	<savepoint name="start17"/>
	<savepoint name="start18"/>
	<savepoint name="start19"/>

	<savepoint name="start20"/>
	<savepoint name="start21"/>
	<savepoint name="start22"/>
	<savepoint name="start23"/>
	<savepoint name="start24"/>
	<savepoint name="start25"/>
	<savepoint name="start26"/>
	<savepoint name="start27"/>
	<savepoint name="start28"/>
	<savepoint name="start29"/>

	<savepoint name="start30"/>
	<savepoint name="start31"/>
	<savepoint name="start32"/>
	<savepoint name="start33"/>
	<savepoint name="start34"/>
	<savepoint name="start35"/>
	<savepoint name="start36"/>
	<savepoint name="start37"/>
	<savepoint name="start38"/>
	<savepoint name="start39"/>

	<savepoint name="start40"/>
	<savepoint name="start41"/>
	<savepoint name="start42"/>
	<savepoint name="start43"/>
	<savepoint name="start44"/>
	<savepoint name="start45"/>
	<savepoint name="start46"/>
	<savepoint name="start47"/>
	<savepoint name="start48"/>
	<savepoint name="start49"/>

	<savepoint name="start50"/>
	<savepoint name="start51"/>
	<savepoint name="start52"/>
	<savepoint name="start53"/>
	<savepoint name="start54"/>
	<savepoint name="start55"/>
	<savepoint name="start56"/>
	<savepoint name="start57"/>
	<savepoint name="start58"/>
	<savepoint name="start59"/>


	<releaseSavepoint name="start59"/>
	<releaseSavepoint name="start58"/>
	<releaseSavepoint name="start57"/>
	<releaseSavepoint name="start56"/>
	<releaseSavepoint name="start55"/>
	<releaseSavepoint name="start54"/>
	<releaseSavepoint name="start53"/>
	<releaseSavepoint name="start52"/>
	<releaseSavepoint name="start51"/>
	<releaseSavepoint name="start50"/>

	<releaseSavepoint name="start49"/>
	<releaseSavepoint name="start48"/>
	<releaseSavepoint name="start47"/>
	<releaseSavepoint name="start46"/>
	<releaseSavepoint name="start45"/>
	<releaseSavepoint name="start44"/>
	<releaseSavepoint name="start43"/>
	<releaseSavepoint name="start42"/>
	<releaseSavepoint name="start41"/>
	<releaseSavepoint name="start40"/>

	<releaseSavepoint name="start39"/>
	<releaseSavepoint name="start38"/>
	<releaseSavepoint name="start37"/>
	<releaseSavepoint name="start36"/>
	<releaseSavepoint name="start35"/>
	<releaseSavepoint name="start34"/>
	<releaseSavepoint name="start33"/>
	<releaseSavepoint name="start32"/>
	<releaseSavepoint name="start31"/>
	<releaseSavepoint name="start30"/>

	<releaseSavepoint name="start29"/>
	<releaseSavepoint name="start28"/>
	<releaseSavepoint name="start27"/>
	<releaseSavepoint name="start26"/>
	<releaseSavepoint name="start25"/>
	<releaseSavepoint name="start24"/>
	<releaseSavepoint name="start23"/>
	<releaseSavepoint name="start22"/>
	<releaseSavepoint name="start21"/>
	<releaseSavepoint name="start20"/>

	<releaseSavepoint name="start19"/>
	<releaseSavepoint name="start18"/>
	<releaseSavepoint name="start17"/>
	<releaseSavepoint name="start16"/>
	<releaseSavepoint name="start15"/>
	<releaseSavepoint name="start14"/>
	<releaseSavepoint name="start13"/>
	<releaseSavepoint name="start12"/>
	<releaseSavepoint name="start11"/>
	<releaseSavepoint name="start10"/>

	<releaseSavepoint name="start9"/>
	<releaseSavepoint name="start8"/>
	<releaseSavepoint name="start7"/>
	<releaseSavepoint name="start6"/>
	<releaseSavepoint name="start5"/>
	<releaseSavepoint name="start4"/>
	<releaseSavepoint name="start3"/>
	<releaseSavepoint name="start2"/>
	<releaseSavepoint name="start1"/>
	<releaseSavepoint name="start0"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/subtransaction/SubTransactionTest/d9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "subtransaction.dtd">
<statements>
	<subtransBegin/>
	<subtransEnd/>

	<subtransBegin/>
	<subtransBegin>
		<delete insertOfStatement="0"/>
		<delete insertOfStatement="2"/>
	</subtransBegin>
	<subtransEnd/>
	<subtransRollback/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/subtransaction/SubTransactionTest/a2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "subtransaction.dtd">
<statements>
	<subtransBegin/>

		<savepoint name="prog1"/>
		<rollbackTo name="prog1"/>
		<rollbackTo name="prog1"/>
		<rollbackTo name="prog1"/>

		<subtransBegin>
			<delete insertOfStatement="1"/>
			<delete insertOfStatement="2"/>
			<delete insertOfStatement="3"/>
			<delete insertOfStatement="4"/>
		</subtransBegin>
		<subtransRollback/>

	<subtransEnd/>

</statements>
