=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/interpreter/TestCasesInterpreter/TestCases.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--Sequence of test cases-->
<!ELEMENT Tests (Test+)>
<!ATTLIST Tests
	Description CDATA #IMPLIED
>

<!--A test case-->
<!--We have one comment, the optional one prepare block, the obligatory one run block,
and the optional one clean up block-->
<!ELEMENT Test (Comment, Prepare?, Run, CleanUp?)>
<!ATTLIST Test
	Number CDATA #REQUIRED
	Responsible CDATA #REQUIRED
	TestType (negative | positive) #REQUIRED
	ErrorType (syntax | semantic) #IMPLIED
	Exclude CDATA #IMPLIED
>

<!ELEMENT Comment (#PCDATA)>

<!--Prepare, Run and CleanUp have to have one or more statements inside-->
<!ELEMENT Prepare (Statement+)>
<!ELEMENT Run (Statement+)>
<!ELEMENT CleanUp (Statement+)>

<!--An SQL statement-->
<!ELEMENT Statement (CallString, Parameter*, (ResultSet? | Error+))>
<!ATTLIST Statement
	verify (true | false) "false"
        ignore (true | false) "false"
	callable (true | false) "false"
	user CDATA #IMPLIED
>

<!ELEMENT CallString (#PCDATA)>

<!ELEMENT Parameter EMPTY>
<!ATTLIST Parameter
	ParamType (IN | OUT | INOUT) #REQUIRED
	DataType CDATA #REQUIRED
	InValue CDATA #IMPLIED
	OutValue CDATA #IMPLIED
>

<!ELEMENT ResultSet (ColumnDefinition+, Row*)>
<!ATTLIST ResultSet
	Verification (Sorted | SortedQuick | Complete | Subset) #REQUIRED
>

<!ELEMENT ColumnDefinition (ColumnName, ColumnType)>
<!ELEMENT ColumnName (#PCDATA)>
<!ELEMENT ColumnType (#PCDATA)>

<!ELEMENT Row (Value+)>
<!ELEMENT Value (#PCDATA)>
<!ATTLIST Value
        Ignore (true) #IMPLIED
        range (true) #IMPLIED
        regex (true) #IMPLIED
>
<!ELEMENT Error (ErrorCode, ErrorMessage)>
<!ELEMENT ErrorCode (#PCDATA)>
<!ELEMENT ErrorMessage (#PCDATA)>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/loader/LoaderTestInterpreter/LOADER_TRANSPORT.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Tests SYSTEM "TestCases.dtd">
<Tests>
<Test Exclude="" Number="1" Responsible="Hans-Georg " TestType="positive">
<Comment/>
<Run>
<Statement callable="false" ignore="false" verify="false">
<CallString>DELETE SYSLOADER.TRANSFORMATIONMODEL
</CallString>
</Statement>
<Statement callable="false" ignore="false" verify="false">
<CallString>USE USER DBA DBA</CallString>
</Statement>
<Statement callable="false" ignore="false" verify="false">
<CallString>SAVE CATALOG    ALL          INTO DBA.CATALOG</CallString>
</Statement>
<Statement callable="false" ignore="false" verify="false">
<CallString>INSERT INTO SYSLOADER.TRANSFORMATIONMODEL ( PACKAGEGUID,     STEPID  ,   CMD,    SEQ_NO,   OWNER,   SCHEMANAME,   TABLENAME,   TABLETYPE ) ( 
SELECT x'0200000004EDADF8BC080000C80F0000885F1FFD9F6E7CD5',  C.CMD_NO, C.CMD,  C.SEQ_NO, C.OWNER, C.SCHEMA    , C.TABLENAME, C.TABLETYPE  
FROM  DBA.CATALOG C, DOMAIN.USERS U  
WHERE   
U.ISREPLICATIONUSER NOT IN ('YES')  AND
C.OWNER         =  U.USERNAME       AND      
C.TYPE      NOT IN ('SYSTEM')       AND
C.SCHEMA    NOT IN ('PUBLIC','SYS') AND 
C.CMD_NO        IN ( SELECT C.CMD_NO  FROM DBA.CATALOG C WHERE 
                          ( C.CMD NOT LIKE 'GRANT %'     AND C.TABLETYPE IN  ( 'TABLE','VIEW','SYNONYM' ) AND C.SEQ_NO = 0 ) OR  
                          ( C.CMD     LIKE 'GRANT %' ) ) AND 
C.TABLENAME NOT IN ('CATALOG','SYSUPGRADEHISTORY') ) </CallString>
</Statement>
<Statement callable="false" ignore="false" verify="true">
<CallString>select distinct(owner) from SYSLOADER.TRANSFORMATIONMODEL WHERE packageguid = x'0200000004EDADF8BC080000C80F0000885F1FFD9F6E7CD5'</CallString>
<ResultSet Verification="Complete">
<ColumnDefinition>
<ColumnName>OWNER</ColumnName>
<ColumnType>CHAR</ColumnType>
</ColumnDefinition>
<Row>
<Value>'LOADER'</Value>
</Row>
</ResultSet>
</Statement>
</Run>
<CleanUp>
<Statement callable="false" ignore="false" verify="false">
<CallString>DROP TABLE DBA.CATALOG</CallString>
</Statement>
</CleanUp>
</Test>
<Test Exclude="" Number="2" Responsible="Hans-Georg " TestType="positive">
<Comment/>
<Run>
<Statement callable="false" ignore="false" verify="false">
<CallString>DELETE SYSLOADER.TRANSFORMATIONMODEL
</CallString>
</Statement>
<Statement callable="false" ignore="false" verify="false">
<CallString>USE USER LOADER LOADER</CallString>
</Statement>
<Statement callable="false" ignore="false" verify="false">
<CallString>SAVE CATALOG    USER          INTO LOADER.CATALOG</CallString>
</Statement>
<Statement callable="false" ignore="false" verify="false">
<CallString>INSERT INTO SYSLOADER.TRANSFORMATIONMODEL ( PACKAGEGUID,     STEPID  ,   CMD,    SEQ_NO,   OWNER,   SCHEMANAME,   TABLENAME,   TABLETYPE ) ( 
SELECT x'0200000004EDADF8BC080000C80F0000885F1FFD9F6E7CD5',  C.CMD_NO, C.CMD,  C.SEQ_NO, C.OWNER, C.SCHEMA    , C.TABLENAME, C.TABLETYPE  
FROM  LOADER.CATALOG C, DOMAIN.USERS U  
WHERE   
U.ISREPLICATIONUSER NOT IN ('YES')   AND
C.OWNER         =  U.USERNAME        AND      
C.TYPE      NOT IN ('SYSTEM')        AND
C.SCHEMA    NOT IN ('PUBLIC','SYS')  AND 
C.CMD_NO        IN ( SELECT C.CMD_NO  FROM LOADER.CATALOG C WHERE 
                          ( C.CMD NOT LIKE 'GRANT %'     AND C.TABLETYPE IN  ( 'TABLE','VIEW','SYNONYM' ) AND C.SEQ_NO = 0 ) OR  
                          ( C.CMD     LIKE 'GRANT %' ) ) AND 
C.TABLENAME NOT IN ('CATALOG','SYSUPGRADEHISTORY') ) </CallString>
</Statement>
<Statement callable="false" ignore="false" verify="true">
<CallString>select distinct(owner)  from SYSLOADER.TRANSFORMATIONMODEL WHERE packageguid = x'0200000004EDADF8BC080000C80F0000885F1FFD9F6E7CD5'</CallString>
<ResultSet Verification="Complete">
<ColumnDefinition>
<ColumnName>OWNER</ColumnName>
<ColumnType>CHAR</ColumnType>
</ColumnDefinition>
<Row>
<Value>'LOADER'</Value>
</Row>
</ResultSet>
</Statement>
</Run>
<CleanUp>
<Statement callable="false" ignore="false" verify="false">
<CallString>DROP TABLE LOADER.CATALOG</CallString>
</Statement>
</CleanUp>
</Test>
<Test Exclude="" Number="3" Responsible="Hans-Georg " TestType="positive">
<Comment/>
<Run>
<Statement callable="false" ignore="false" verify="false">
<CallString>DELETE SYSLOADER.TRANSFORMATIONMODEL
</CallString>
</Statement>
<Statement callable="false" ignore="false" verify="false">
<CallString>USE USER LOADER LOADER SCHEMA LOAD_SCHEMA_TEST501</CallString>
</Statement>
<Statement callable="false" ignore="false" verify="false">
<CallString>SAVE CATALOG OF SCHEMA LOAD_SCHEMA_TEST501     INTO LOAD_SCHEMA_TEST501.CATALOG
</CallString>
</Statement>
<Statement callable="false" ignore="false" verify="false">
<CallString>INSERT INTO SYSLOADER.TRANSFORMATIONMODEL ( PACKAGEGUID,     STEPID  ,   CMD,    SEQ_NO,   OWNER,   SCHEMANAME,   TABLENAME,   TABLETYPE ) ( 
SELECT x'0200000004EDADF8BC080000C80F0000885F1FFD9F6E7CD5',  C.CMD_NO, C.CMD,  C.SEQ_NO, C.OWNER, C.SCHEMA    , C.TABLENAME, C.TABLETYPE  
FROM  LOAD_SCHEMA_TEST501.CATALOG C, DOMAIN.USERS U  
WHERE   
U.ISREPLICATIONUSER NOT IN ('YES')   AND
C.OWNER         =  U.USERNAME        AND      
C.TYPE      NOT IN ('SYSTEM')        AND
C.SCHEMA    NOT IN ('PUBLIC','SYS')  AND 
C.CMD_NO        IN ( SELECT C.CMD_NO  FROM LOAD_SCHEMA_TEST501.CATALOG C WHERE 
                          ( C.CMD NOT LIKE 'GRANT %'     AND C.TABLETYPE IN  ( 'TABLE','VIEW','SYNONYM' ) AND C.SEQ_NO = 0 ) OR  
                          ( C.CMD     LIKE 'GRANT %' ) ) AND 
C.TABLENAME NOT IN ('CATALOG','SYSUPGRADEHISTORY') ) </CallString>
</Statement>
<Statement callable="false" ignore="false" verify="true">
<CallString>select distinct(schemaname)  from SYSLOADER.TRANSFORMATIONMODEL WHERE packageguid = x'0200000004EDADF8BC080000C80F0000885F1FFD9F6E7CD5'</CallString>
<ResultSet Verification="Complete">
<ColumnDefinition>
<ColumnName>SCHEMANAME</ColumnName>
<ColumnType>CHAR</ColumnType>
</ColumnDefinition>
<Row>
<Value>'LOAD_SCHEMA_TEST501'</Value>
</Row>
</ResultSet>
</Statement>
</Run>
<CleanUp>
<Statement callable="false" ignore="false" verify="false">
<CallString>DROP TABLE LOAD_SCHEMA_TEST501.CATALOG</CallString>
</Statement>
</CleanUp>
</Test>
<Test Exclude="" Number="4" Responsible="Hans-Georg " TestType="positive">
<Comment/>
<Run>
<Statement callable="false" ignore="false" verify="false">
<CallString>DELETE SYSLOADER.TRANSFORMATIONMODEL
</CallString>
</Statement>
<Statement callable="false" ignore="false" verify="false">
<CallString>USE USER LOADER LOADER SCHEMA FLOAD_SCHEMA_TEST501</CallString>
</Statement>
<Statement callable="false" ignore="false" verify="false">
<CallString>SAVE CATALOG OF FLOAD_SCHEMA_TEST501.FLOAD_TEST501 INTO FLOAD_SCHEMA_TEST501.CATALOG
</CallString>
</Statement>
<Statement callable="false" ignore="false" verify="false">
<CallString>INSERT INTO SYSLOADER.TRANSFORMATIONMODEL ( PACKAGEGUID,     STEPID  ,   CMD,    SEQ_NO,   OWNER,   SCHEMANAME,   TABLENAME,   TABLETYPE ) ( 
SELECT x'0200000004EDADF8BC080000C80F0000885F1FFD9F6E7CD5',  C.CMD_NO, C.CMD,  C.SEQ_NO, C.OWNER, C.SCHEMA    , C.TABLENAME, C.TABLETYPE  
FROM  FLOAD_SCHEMA_TEST501.CATALOG C, DOMAIN.USERS U  
WHERE   
U.ISREPLICATIONUSER NOT IN ('YES')  AND
C.OWNER         =  U.USERNAME       AND      
C.TYPE      NOT IN ('SYSTEM')       AND
C.SCHEMA    NOT IN ('PUBLIC','SYS') AND 
C.CMD_NO        IN ( SELECT C.CMD_NO  FROM FLOAD_SCHEMA_TEST501.CATALOG C WHERE 
                          ( C.CMD NOT LIKE 'GRANT %'     AND C.TABLETYPE IN  ( 'TABLE','VIEW','SYNONYM' ) AND C.SEQ_NO = 0 ) OR  
                          ( C.CMD     LIKE 'GRANT %' ) ) AND 
C.TABLENAME NOT IN ('CATALOG','SYSUPGRADEHISTORY') ) </CallString>
</Statement>
<Statement callable="false" ignore="false" verify="true">
<CallString>select distinct(tablename)  from SYSLOADER.TRANSFORMATIONMODEL WHERE packageguid = x'0200000004EDADF8BC080000C80F0000885F1FFD9F6E7CD5'</CallString>
<ResultSet Verification="Complete">
<ColumnDefinition>
<ColumnName>TABLENAME</ColumnName>
<ColumnType>CHAR</ColumnType>
</ColumnDefinition>
<Row>
<Value>'FLOAD_TEST501'</Value>
</Row>
</ResultSet>
</Statement>
</Run>
<CleanUp>
<Statement callable="false" ignore="false" verify="false">
<CallString>DROP TABLE FLOAD_SCHEMA_TEST501.CATALOG</CallString>
</Statement>
</CleanUp>
</Test>
</Tests>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/loader/LoaderTestInterpreter/LOADER_EXTRACT.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Tests SYSTEM "TestCases.dtd">
<Tests>
<Test Exclude="" Number="1" Responsible="Steffen Schildberg" TestType="positive">
<Comment>Test for PTS 1134919: Not all data of a table extracted because of a wrong computed packet size</Comment>
<Prepare>
<Statement callable="false" ignore="false"  verify="false">
<CallString>CREATE TABLE extract_test1(kseq integer, k500k integer, k250k integer, k100k integer, k40k integer,
k10k integer, k1k integer, k100 integer, k25 integer, k10 integer, k5 integer, k4 integer, k2 integer,
s1 char(8), s2 char(20), s3 char(20), s4 char(20), s5 char(20), s6 char(20),  s7 char(20), s8 char(20), primary key (kseq))</CallString>
</Statement>
</Prepare>
<Run>
<Statement callable="false" ignore="false"  verify="false">
<CallString>LOAD TABLE extract_test1
DATA INSTREAM FILE '&lt;infile_path&gt;extract_test1.data' COMPRESSED</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>EXTRACT TABLE extract_test1
DATA OUTSTREAM FILE '&lt;infile_path&gt;extract_test1_generated.data' PAGES</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>DELETE extract_test1</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>LOAD TABLE extract_test1
DATA INSTREAM FILE '&lt;infile_path&gt;extract_test1_generated.data' PAGES</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="true">
<CallString>SELECT COUNT(*) FROM extract_test1</CallString>
<ResultSet Verification="Complete">
<ColumnDefinition>
<ColumnName>EXPRESSION1</ColumnName>
<ColumnType>FIXED</ColumnType>
</ColumnDefinition>
<Row>
<Value>2500</Value>
</Row>
</ResultSet>
</Statement>
</Run>
</Test>
<Test Exclude="" Number="1131747" Responsible="Steffen Schildberg" TestType="positive">
<Comment>Check various possibilities to specify table names in Loader commands: names contain quotes itself</Comment>
<Prepare>
<Statement callable="false" ignore="false"  verify="false">
<CallString>CREATE TABLE "EXTRACT_""TEST1131747" ("A""A" INT, "B""""B" CHAR(10))</CallString>
</Statement>
</Prepare>
<Run>
<Statement callable="false" ignore="false"  verify="false">
<CallString>DATALOAD TABLE "EXTRACT_""TEST1131747"
INFILE '&lt;infile_path&gt;load_test1131747.data' </CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>EXPORT TABLE "EXTRACT_""TEST1131747"
DATA OUTSTREAM FILE '&lt;infile_path&gt;extract_test1131747_generated_records.data'  records</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>DELETE "EXTRACT_""TEST1131747"</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>IMPORT TABLE "EXTRACT_""TEST1131747"
DATA INSTREAM FILE '&lt;infile_path&gt;extract_test1131747_generated_records.data'  records</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="true">
<CallString>SELECT COUNT(*) FROM "EXTRACT_""TEST1131747"</CallString>
<ResultSet Verification="Complete">
<ColumnDefinition>
<ColumnName>EXPRESSION1</ColumnName>
<ColumnType>FIXED</ColumnType>
</ColumnDefinition>
<Row>
<Value>3</Value>
</Row>
</ResultSet>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>EXPORT TABLE "EXTRACT_""TEST1131747"
DATA OUTSTREAM FILE '&lt;infile_path&gt;extract_test1131747_generated_pages.data'  pages</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>DELETE "EXTRACT_""TEST1131747"</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>IMPORT TABLE "EXTRACT_""TEST1131747"
DATA INSTREAM FILE '&lt;infile_path&gt;extract_test1131747_generated_pages.data'  pages</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="true">
<CallString>SELECT COUNT(*) FROM "EXTRACT_""TEST1131747"</CallString>
<ResultSet Verification="Complete">
<ColumnDefinition>
<ColumnName>EXPRESSION1</ColumnName>
<ColumnType>FIXED</ColumnType>
</ColumnDefinition>
<Row>
<Value>3</Value>
</Row>
</ResultSet>
</Statement>
</Run>
</Test>
<Test ErrorType="syntax" Exclude="" Number="1134813" Responsible="Steffen Schildberg" TestType="negative">
<Comment>test extract date values if the date and time format of the kernel is set to a format other than INTERNAL
PTS 1134813</Comment>
<Prepare>
<Statement callable="false" ignore="false"  verify="false">
<CallString>CREATE TABLE extract_test1134813(a date, b integer)</CallString>
</Statement>
</Prepare>
<Run>
<Statement callable="false" ignore="false"  verify="false">
<CallString>SET FORMAT ISO</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>INSERT INTO extract_test1134813 values ('1998-01-01', 1)</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>INSERT INTO extract_test1134813 values ('1999-01-01', 2)</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>INSERT INTO extract_test1134813 values ('2000-01-01', 3)</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>DATAEXTRACT * FROM extract_test1134813 OUTFIELDS
a 1
b 2
OUTFILE '&lt;infile_path&gt;extract_test1134813_generated.data'
DATE ISO</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>SET FORMAT INTERNAL</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>DELETE extract_test1134813</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>LOAD TABLE extract_test1134813
DATA INSTREAM FILE '&lt;infile_path&gt;extract_test1134813_generated.data'
DATE ISO</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="true">
<CallString>SELECT * FROM extract_test1134813</CallString>
<ResultSet Verification="Complete">
<ColumnDefinition>
<ColumnName>A</ColumnName>
<ColumnType>DATE</ColumnType>
</ColumnDefinition>
<ColumnDefinition>
<ColumnName>B</ColumnName>
<ColumnType>INT</ColumnType>
</ColumnDefinition>
<Row>
<Value>'1998-01-01'</Value>
<Value>1</Value>
</Row>
<Row>
<Value>'1999-01-01'</Value>
<Value>2</Value>
</Row>
<Row>
<Value>'2000-01-01'</Value>
<Value>3</Value>
</Row>
</ResultSet>
</Statement>
</Run>
</Test>
<Test Exclude="" Number="1136604" Responsible="Steffen Schildberg" TestType="positive">
<Comment>Tests releasing locks after unsuccessful export of data of a single table. The error is only simulated by a row not found error (requesting to start
extraction with row 3 where the table contains only 1 row of data) which would as any other error lock the table.
PTS 1136604</Comment>
<Prepare>
<Statement callable="false" ignore="false"  verify="false">
<CallString>CREATE TABLE extract_test1136604(a char(3))</CallString>
</Statement>
</Prepare>
<Run>
<Statement callable="false" ignore="false"  verify="false">
<CallString>INSERT INTO extract_test1136604 values ('111')</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>EXPORT TABLE extract_test1136604 
DATA OUTSTREAM FILE '&lt;infile_path&gt;extract_test1136604_generated.data'
START 3 10</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="true">
<CallString>SELECT count(*) FROM locks where tablename = 'EXTRACT_TEST1136604'</CallString>
<ResultSet Verification="Complete">
<ColumnDefinition>
<ColumnName>EXPRESSION1</ColumnName>
<ColumnType>FIXED</ColumnType>
</ColumnDefinition>
<Row>
<Value>0</Value>
</Row>
</ResultSet>
</Statement>
</Run>
</Test>
</Tests>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/loader/LoaderTestInterpreter/ImportTableSyntax.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Tests SYSTEM "TestCases.dtd">
<Tests>
<Test Exclude="" Number="1" Responsible="Ileana Somesan" TestType="positive">
<Comment>Load data of 2 columns of the table import_table.test51 into table import_table.test251 in format RECORDS; the test extracts the data itself</Comment>
<Prepare>
<Statement callable="false" ignore="false"  verify="false">
<CallString>CREATE TABLE import_table.test252 (a CHAR(10), b CHAR(10), c CHAR(10), PRIMARY KEY(a))</CallString>
</Statement>
</Prepare>
<Run>
<Statement callable="false" ignore="false"  verify="false">
<CallString>EXPORT COLUMNS a,b  from import_table.test51
data outstream  '&lt;infile_path&gt;load_test252_generated.data' RECORDS
</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="false">
<CallString>IMPORT TABLE import_table.test252
DATA INSTREAM  '&lt;infile_path&gt;load_test252_generated.data' RECORDS
A   1
B   2

</CallString>
</Statement>
<Statement callable="false" ignore="false"  verify="true">
<CallString>SELECT * FROM import_table.test252</CallString>
<ResultSet Verification="Complete">
<ColumnDefinition>
<ColumnName>A</ColumnName>
<ColumnType>CHAR</ColumnType>
</ColumnDefinition>
<ColumnDefinition>
<ColumnName>B</ColumnName>
<ColumnType>CHAR</ColumnType>
</ColumnDefinition>
<ColumnDefinition>
<ColumnName>C</ColumnName>
<ColumnType>CHAR</ColumnType>
</ColumnDefinition>
<Row>
<Value>'aaa'</Value>
<Value>'klmno'</Value>
<Value>NULL</Value>
</Row>
<Row>
<Value>'aab'</Value>
<Value>'klmno'</Value>
<Value>NULL</Value>
</Row>
<Row>
<Value>'bbb'</Value>
<Value>'klmno'</Value>
<Value>NULL</Value>
</Row>
<Row>
<Value>'ccc'</Value>
<Value>'klmno'</Value>
<Value>NULL</Value>
</Row>
<Row>
<Value>'d_p'</Value>
<Value>'klmno'</Value>
<Value>NULL</Value>
</Row>
<Row>
<Value>'jjH4'</Value>
<Value>'kljf'</Value>
<Value>NULL</Value>
</Row>
<Row>
<Value>'mmKU'</Value>
<Value>'arhg'</Value>
<Value>NULL</Value>
</Row>
<Row>
<Value>'ooTD'</Value>
<Value>'atzt'</Value>
<Value>NULL</Value>
</Row>
</ResultSet>
</Statement>
</Run>
</Test>
<Test ErrorType="syntax" Exclude="" Number="2" Responsible="Ileana Somesan" TestType="negative">
<Comment>Test file format options syntactically: 
- codeset not available as option
- only possible codetypes are UCS2, UTF8 and ASCII
- only possible format specifications in case of data streams are FORMATTED, COMPRESSED, PAGES, RECORDS
</Comment>
<Run>
<Statement callable="false" ignore="true" verify="false">
<CallString>IMPORT TABLE import_table.test1 DATA INSTREAM  'test.data' codeset ISO8859-1</CallString>
<Error>
<ErrorCode>-25281</ErrorCode>
<ErrorMessage>Syntax error</ErrorMessage>
</Error>
</Statement>
<Statement callable="false" ignore="true" verify="false">
<CallString>IMPORT TABLE import_table.test1 DATA INSTREAM  'test.data' some_name</CallString>
<Error>
<ErrorCode>-25281</ErrorCode>
<ErrorMessage>Syntax error</ErrorMessage>
</Error>
</Statement>
<Statement callable="false" ignore="true" verify="false">
<CallString>IMPORT TABLE import_table.test1
DATA INSTREAM  'test.data' COMPRESS 
A 1
B 2
</CallString>
<Error>
<ErrorCode>-25281</ErrorCode>
<ErrorMessage>Syntax error</ErrorMessage>
</Error>
</Statement>
<Statement callable="false" ignore="true" verify="false">
<CallString>IMPORT TABLE import_table.test1
DATA INSTREAM  'test.data' FORMATT
A 1- 10
B 11 - 20
</CallString>
<Error>
<ErrorCode>-25233</ErrorCode>
<ErrorMessage>Some column descriptions with end position but file format is COMPRESSED.</ErrorMessage>
</Error>
</Statement>
</Run>
</Test>
<Test ErrorType="syntax" Exclude="" Number="3" Responsible="Ileana Somesan" TestType="negative">
<Comment>Test external column data types syntactically:
1. INTEGER requires file format FORMATTED; no need to create the table nor to have the data file
2. INTEGER requires 2 or 4 Byte long fields</Comment>
<Run>
<Statement callable="false" ignore="false" verify="false">
<CallString>IMPORT TABLE import_table.test5
DATA INSTREAM  'load_test5.data'
A  1 INTEGER
B 2
</CallString>
<Error>
<ErrorCode>-25216</ErrorCode>
<ErrorMessage>File option FORMATTED required.</ErrorMessage>
</Error>
</Statement>
<Statement callable="false" ignore="false" verify="false">
<CallString>IMPORT TABLE import_table.test5
DATA INSTREAM  'load_test5.data' FWV
A  1-3   INTEGER
B  4-8  
</CallString>
<Error>
<ErrorCode>-25201</ErrorCode>
<ErrorMessage>Column "A" - INTEGER field: 1, 2 or 4 bytes long, (double if HEX).</ErrorMessage>
</Error>
</Statement>
<Statement callable="false" ignore="false" verify="false">
<CallString>IMPORT TABLE import_table.test5
DATA INSTREAM  'load_test5.data' FWV
A  1-5   INTEGER
B  6-10  
</CallString>
<Error>
<ErrorCode>-25201</ErrorCode>
<ErrorMessage>Column "A" - INTEGER field: 1, 2 or 4 bytes long, (double if HEX).</ErrorMessage>
</Error>
</Statement>
</Run>
</Test>
</Tests>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/loader/LoaderTestInterpreter/ExportDB_V77nachV77.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Tests SYSTEM "TestCases.dtd">
<Tests>
<Test ErrorType="syntax" Exclude="" Number="1" Responsible="" TestType="negative">
<Comment/>
<Run>
<Statement callable="false" ignore="false" verify="false">
<CallString>EXPORT DB 
CATALOG OUTSTREAM '&lt;infile_path&gt;Ev77_test1_pages.catalog'
DATA OUTSTREAM '&lt;infile_path&gt;Ev77_test1_pages.data'  PAGES</CallString>
<Error>
<ErrorCode>-25331</ErrorCode>
<ErrorMessage>This is a restricted statement, user must be SYSDBA</ErrorMessage>
</Error>
</Statement>
<Statement callable="false" ignore="false" verify="false">
<CallString>EXPORT DB 
CATALOG OUTSTREAM '&lt;infile_path&gt;Ev77_test1_records.catalog'
DATA OUTSTREAM '&lt;infile_path&gt;Ev77_test1_records.data' RECORDS</CallString>
<Error>
<ErrorCode>-25331</ErrorCode>
<ErrorMessage>This is a restricted statement, user must be SYSDBA</ErrorMessage>
</Error>
</Statement>
</Run>
</Test>
</Tests>
