<?xml version="1.0"?>
<!-- internal DTD -->
<!DOCTYPE MsgServerConfiguration [

<!ELEMENT MsgServerConfiguration (ServerGeneral,
                                  MsgServerDataBase,
                                  TransientStorage,
                                  Topics,
                                  Queues,
                                  MsgServer,
                                  MsgServerDebug)>

<!ELEMENT ServerGeneral (MaxConnections,
                         LogFilename,
                         SSLConnection,
                         AdminPassword,
                         AdminPort,
                         JndiPort,
                         MsgPort)>
  <!ELEMENT MaxConnections (#PCDATA)> 
  <!ELEMENT LogFilename    (#PCDATA)> 
  <!ELEMENT SSLConnection  (#PCDATA)> 
  <!ELEMENT AdminPassword  (#PCDATA)> 
  <!ELEMENT AdminPort      (#PCDATA)> 
  <!ELEMENT JndiPort       (#PCDATA)> 
  <!ELEMENT MsgPort        (#PCDATA)>  

<!ELEMENT MsgServerDataBase (DatabaseURL, JDBCDriver, User, Password,Schema)>
    <!ELEMENT DatabaseURL (#PCDATA)>
    <!ELEMENT JDBCDriver (#PCDATA)>
    <!ELEMENT User (#PCDATA)>
    <!ELEMENT Password (#PCDATA)>
    <!ELEMENT Schema (#PCDATA)>

<!ELEMENT TransientStorage (TransientDatabaseURL,
                            TransientJDBCDriver,
                            TransientUser,
                            TransientPassword,
                            TransientMaxSendOrders,
                            TransientMaxMessageSpaceInKB,
                            TransientPushSizeForSendOrderQueue)>
    <!ELEMENT TransientDatabaseURL (#PCDATA)>
    <!ELEMENT TransientJDBCDriver (#PCDATA)>
    <!ELEMENT TransientUser (#PCDATA)>
    <!ELEMENT TransientPassword (#PCDATA)>
    <!ELEMENT TransientMaxSendOrders (#PCDATA)>
    <!ELEMENT TransientMaxMessageSpaceInKB (#PCDATA)>
    <!ELEMENT TransientPushSizeForSendOrderQueue (#PCDATA)>


<!ELEMENT Topics (TopicName)+>
    <!ELEMENT TopicName (#PCDATA)>

<!ELEMENT Queues (QueueName)+>
    <!ELEMENT QueueName (#PCDATA)>

<!ELEMENT MsgServer (Agents, InitialDBConnections, SendOrderPollingInMilliSec,
                        LengthSendOrderQueue, PushSizeForSendOrderQueue,
                        MessageCacheSizeInKB, GarbageCollectingTimeInSec,
                        ClientTimeOutInSec,CreateMsgSvrTables)>
    <!ELEMENT Agents (#PCDATA)>
    <!ELEMENT InitialDBConnections (#PCDATA)>
    <!ELEMENT SendOrderPollingInMilliSec (#PCDATA)>
    <!ELEMENT LengthSendOrderQueue (#PCDATA)>
    <!ELEMENT PushSizeForSendOrderQueue (#PCDATA)>
    <!ELEMENT MessageCacheSizeInKB (#PCDATA)>
    <!ELEMENT GarbageCollectingTimeInSec (#PCDATA)>
    <!ELEMENT ClientTimeOutInSec (#PCDATA)>
    <!ELEMENT CreateMsgSvrTables (#PCDATA)>

<!ELEMENT MsgServerDebug (DisplayServerStateInSec, 
			      VerboseAdmin,
			      VerboseConsumer,
			      VerboseException,
			      VerboseMessageBuilder,
			      VerboseSendingQueues, 
			      VerboseSendOrderStat,
			      VerboseSendReceive,
			      VerboseSQLConnection,
			      VerboseTraceBack,
			      VerboseWait,
			      ServerSendTrace)>
    <!ELEMENT DisplayServerStateInSec (#PCDATA)>
    <!ELEMENT VerboseAdmin (#PCDATA)>
    <!ELEMENT VerboseConsumer (#PCDATA)>
    <!ELEMENT VerboseException (#PCDATA)>
    <!ELEMENT VerboseMessageBuilder (#PCDATA)>
    <!ELEMENT VerboseSendingQueues (#PCDATA)>
    <!ELEMENT VerboseSendOrderStat (#PCDATA)>
    <!ELEMENT VerboseSendReceive (#PCDATA)>
    <!ELEMENT VerboseSQLConnection (#PCDATA)>
    <!ELEMENT VerboseTraceBack (#PCDATA)>
    <!ELEMENT VerboseWait (#PCDATA)>    
    <!ELEMENT ServerSendTrace (#PCDATA)>

]>

<!-- DATA -->

<MsgServerConfiguration>

    <ServerGeneral>
	<MaxConnections>100</MaxConnections> 
	<LogFilename /> 
	<SSLConnection>0</SSLConnection> 
	<AdminPassword></AdminPassword> 
	<AdminPort></AdminPort> 
	<JndiPort></JndiPort>
	<MsgPort></MsgPort>
    </ServerGeneral>

    <MsgServerDataBase>
	<DatabaseURL></DatabaseURL>
        <JDBCDriver>com.sap.dbtech.jdbc.DriverSapDB</JDBCDriver>
        <User></User>
        <Password></Password>
        <Schema>MESSAGESERVICE</Schema>
    </MsgServerDataBase>

     <TransientStorage>
        <TransientDatabaseURL><![CDATA[jdbc:transientStorage://]]></TransientDatabaseURL>
        <TransientJDBCDriver>com.sap.sdb.msgServer.transientStorage.DriverImpl</TransientJDBCDriver>
        <TransientUser />
        <TransientPassword  />
        <TransientMaxSendOrders>100000</TransientMaxSendOrders>
        <TransientMaxMessageSpaceInKB>32000</TransientMaxMessageSpaceInKB>
        <TransientPushSizeForSendOrderQueue>250</TransientPushSizeForSendOrderQueue>
    </TransientStorage>

    <Topics>
        <TopicName>TestTopic hallo, hallo</TopicName>
        <TopicName>MapTopic  hallo, hallo</TopicName>
        <TopicName>TextTopic hallo, hallo</TopicName>
    </Topics>

    <Queues>
        <QueueName>TestQueue hallo, hallo</QueueName>
        <QueueName>MapQueue  hallo, hallo</QueueName>
        <QueueName>TextQueue hallo, hallo</QueueName>
    </Queues>

    <MsgServer>
        <Agents>2</Agents>
        <InitialDBConnections>5</InitialDBConnections>
        <SendOrderPollingInMilliSec>600000000</SendOrderPollingInMilliSec>
        <LengthSendOrderQueue>1000</LengthSendOrderQueue>
        <PushSizeForSendOrderQueue>50</PushSizeForSendOrderQueue>
        <MessageCacheSizeInKB>16000</MessageCacheSizeInKB>
        <GarbageCollectingTimeInSec>3600</GarbageCollectingTimeInSec>
        <ClientTimeOutInSec>6000</ClientTimeOutInSec>
	<CreateMsgSvrTables>1</CreateMsgSvrTables>
    </MsgServer>

    <MsgServerDebug>
        <DisplayServerStateInSec>100000</DisplayServerStateInSec>
        <VerboseAdmin>0</VerboseAdmin> 
	<VerboseConsumer>0</VerboseConsumer> 
	<VerboseException>1</VerboseException> 
	<VerboseMessageBuilder>0</VerboseMessageBuilder> 
	<VerboseSendingQueues>0</VerboseSendingQueues> 
	<VerboseSendOrderStat>0</VerboseSendOrderStat> 
	<VerboseSendReceive>0</VerboseSendReceive> 
	<VerboseSQLConnection>0</VerboseSQLConnection> 
	<VerboseTraceBack>1</VerboseTraceBack> 
	<VerboseWait>0</VerboseWait> 
        <ServerSendTrace></ServerSendTrace>
    </MsgServerDebug>

</MsgServerConfiguration>
