<?xml version="1.0"?>
<!-- internal DTD -->
<!DOCTYPE TestConfiguration [

<!ELEMENT TestConfiguration (SourceDataBase, TargetDataBase, Source, Target)>

<!ELEMENT SourceDataBase (SourceDatabaseURL, SourceJDBCDriver, SourceUser, SourcePassword)>
    <!ELEMENT SourceDatabaseURL (#PCDATA)>
    <!ELEMENT SourceJDBCDriver (#PCDATA)>
    <!ELEMENT SourceUser (#PCDATA)>
    <!ELEMENT SourcePassword (#PCDATA)>

<!ELEMENT TargetDataBase (TargetDatabaseURL, TargetJDBCDriver, TargetUser, TargetPassword)>
    <!ELEMENT TargetDatabaseURL (#PCDATA)>
    <!ELEMENT TargetJDBCDriver (#PCDATA)>
    <!ELEMENT TargetUser (#PCDATA)>
    <!ELEMENT TargetPassword (#PCDATA)>


<!ELEMENT Source (SourceSQL)+>
    <!ELEMENT SourceSQL (#PCDATA)>
<!ELEMENT Target (TargetSQL)+>
    <!ELEMENT TargetSQL (#PCDATA)>


]>

<!-- DATA -->
<TestConfiguration>
   <SourceDataBase>
      <SourceDatabaseURL>jdbc:sapdb://localhost/sy76s?timeout=0</SourceDatabaseURL>
      <SourceJDBCDriver>com.sap.dbtech.jdbc.DriverSapDB</SourceJDBCDriver>
      <SourceUser>DBSERVICE</SourceUser>
      <SourcePassword>SECRET</SourcePassword>
   </SourceDataBase>
   <TargetDataBase>
      <TargetDatabaseURL>jdbc:sapdb://localhost/sy76t?timeout=0</TargetDatabaseURL>
      <TargetJDBCDriver>com.sap.dbtech.jdbc.DriverSapDB</TargetJDBCDriver>
      <TargetUser>DBSERVICE</TargetUser>
      <TargetPassword>SECRET</TargetPassword>
   </TargetDataBase>

     <Source>
     	<SourceSQL>select cno,firstname,name,title from USER_MASTER.CUSTOMER</SourceSQL>
     	<SourceSQL>select rno,arrival,departure,cno from USER_MASTER.RESERVATION where (arrival > '2004-11-01')</SourceSQL>
       <SourceSQL>select * from USER_MASTER.CUSTOMER</SourceSQL>
    </Source>

    <Target>
     	<TargetSQL>select guest,firstname,surname,title from USER2_CLIENT.GUEST</TargetSQL>
     	<TargetSQL>select id,arrival,departure,guest from USER2_CLIENT.BOOKING</TargetSQL>
        <TargetSQL>select * from USER1_CLIENT.CUSTOMER</TargetSQL>
    </Target>

</TestConfiguration>
