=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/upgradetest/UpgradeTest/testrun.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT testrun (environment, (test|testrow)*)>
<!ATTLIST testrun description CDATA #IMPLIED>
	<!ELEMENT environment (os,bit,platform)>
		<!ELEMENT os (#PCDATA)>
		<!ELEMENT bit (#PCDATA)>
		<!ELEMENT platform (#PCDATA)>

	<!ELEMENT test (version,version,stop,(updateNewSecurityConcept|updateNewSecurityConceptBackup)?,instprofile,database)>
		<!ELEMENT instprofile (#PCDATA)>

		<!ELEMENT version (versionnumber)>
		<!ATTLIST version role NMTOKEN #REQUIRED>
			<!ELEMENT versionnumber (#PCDATA)>
		
		<!ELEMENT stop (EMPTY)>
		<!ATTLIST stop after NMTOKEN #REQUIRED>
		<!ATTLIST stop when  NMTOKEN #IMPLIED>
		<!ATTLIST stop method NMTOKEN #REQUIRED>

		<!ELEMENT updateNewSecurityConcept EMPTY>
		<!ELEMENT updateNewSecurityConceptBackup EMPTY>

		<!ELEMENT database (type,script+)>
			<!ELEMENT type (#PCDATA)>
			<!ELEMENT script (path,dbm?)>
			<!ATTLIST script task NMTOKEN #REQUIRED>
				<!ELEMENT path (#PCDATA)>
				<!ELEMENT dbm (property+)>
					<!ELEMENT property EMPTY>
					<!ATTLIST property name NMTOKEN #REQUIRED>
					<!ATTLIST property value NMTOKEN #REQUIRED>

	<!ELEMENT testrow (version,version,version,(updateNewSecurityConcept|updateNewSecurityConceptBackup)?,instprofile,database)>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/upgradetest/UpgradeTest/tests/win32_alltests.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE testrun SYSTEM "../testrun.dtd">
<testrun description="UpgradeTest (alle Tests)">
	<environment>
		<os> </os>
		<bit> </bit>
		<platform> </platform>
	</environment>
	<testrow> <!-- 7.3.00 auf 7.3.00 -->
		<version role="source-start"><versionnumber>7.3.00.36</versionnumber></version>
		<version role="source-end"><versionnumber>7.3.00.45</versionnumber></version>
		<version role="target"><versionnumber>7.3.00.46</versionnumber></version>
		<version role="brick"><versionnumber>7.4.02.10</versionnumber></version>
		<instprofile>Server</instprofile>
		<database>
			<type>OLTP</type>
			<script task="createdb">
				<path>f7300t7403/createdb.script</path>
			</script>
			<script task="prepupdate">
				<path>f7300t7403/prepupdate.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
			<script task="prepuninst">
				<path>f7300t7403/prepuninst.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
		</database>
	</testrow>
	<testrow> <!-- 7.3.00 auf 7.4.03 -->
		<version role="source-start"><versionnumber>7.3.00.36</versionnumber></version>
		<version role="source-end"><versionnumber>7.3.00.46</versionnumber></version>
		<version role="target"><versionnumber state="DEV">7.4.03</versionnumber></version>
		<version role="brick"><versionnumber>7.4.02.10</versionnumber></version>
		<instprofile>Server</instprofile>
		<database>
			<type>OLTP</type>
			<script task="createdb">
				<path>f7300t7403/createdb.script</path>
			</script>
			<script task="prepupdate">
				<path>f7300t7403/prepupdate.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
			<script task="prepuninst">
				<path>f7300t7403/prepuninst.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
		</database>
	</testrow>
	<testrow> <!-- 7.3.00 auf 7.5.00 -->
		<version role="source-start"><versionnumber>7.3.00.36</versionnumber></version>
		<version role="source-end"><versionnumber>7.3.00.46</versionnumber></version>
		<version role="target"><versionnumber state="DEV">7.5.00</versionnumber></version>
		<version role="brick"><versionnumber>7.4.02.10</versionnumber></version>
		<instprofile>Server</instprofile>
		<database>
			<type>OLTP</type>
			<script task="createdb">
				<path>f7300t7403/createdb.script</path>
			</script>
			<script task="prepupdate">
				<path>f7300t7403/prepupdate.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
			<script task="prepuninst">
				<path>f7300t7403/prepuninst.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
		</database>
	</testrow>
	<!--testrow> <!- 7.4.02 auf 7.4.02 ->
		<version role="source-start"><versionnumber>7.4.02.08</versionnumber></version>
		<version role="source-end"><versionnumber>7.4.02.23</versionnumber></version>
		<version role="target"><versionnumber state="DEV">7.4.02</versionnumber></version>
		<version role="brick"><versionnumber>7.4.03.10</versionnumber></version>
		<instprofile>Server</instprofile>
		<database>
			<type>OLTP</type>
			<script task="createdb">
				<path>f7403t7403/createdb.script</path>
			</script>
			<script task="prepupdate">
				<path>f7403t7403/prepupdate.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
			<script task="prepuninst">
				<path>f7403t7403/prepuninst.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
		</database>
	</testrow>
	<testrow> <!- 7.4.02 auf 7.4.03 ->
		<version role="source-start"><versionnumber>7.4.02.08</versionnumber></version>
		<version role="source-end"><versionnumber>7.4.02.23</versionnumber></version>
		<version role="target"><versionnumber state="DEV">7.4.03</versionnumber></version>
		<version role="brick"><versionnumber>7.4.03.11</versionnumber></version>
		<instprofile>Server</instprofile>
		<database>
			<type>OLTP</type>
			<script task="createdb">
				<path>f7403t7403/createdb.script</path>
			</script>
			<script task="prepupdate">
				<path>f7403t7403/prepupdate.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
			<script task="prepuninst">
				<path>f7403t7403/prepuninst.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
		</database>
	</testrow>
	<testrow> <!- 7.4.02 auf 7.5.00 ->
		<version role="source-start"><versionnumber>7.4.02.08</versionnumber></version>
		<version role="source-end"><versionnumber>7.4.02.23</versionnumber></version>
		<version role="target"><versionnumber state="DEV">7.5.00</versionnumber></version>
		<version role="brick"><versionnumber>7.5.00.02</versionnumber></version>
		<instprofile>Server</instprofile>
		<database>
			<type>OLTP</type>
			<script task="createdb">
				<path>f7403t7403/createdb.script</path>
			</script>
			<script task="prepupdate">
				<path>f7403t7403/prepupdate.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
			<script task="prepuninst">
				<path>f7403t7403/prepuninst.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
		</database>
	</testrow-->
	<testrow> <!-- 7.4.03 auf 7.4.03 -->
		<version role="source-start"><versionnumber>7.4.03.07</versionnumber></version>
		<version role="source-end"><versionnumber>7.4.03.31</versionnumber></version>
		<version role="target"><versionnumber state="DEV">7.4.03</versionnumber></version>
		<version role="brick"><versionnumber>7.5.00.02</versionnumber></version>
		<instprofile>Server</instprofile>
		<database>
			<type>OLTP</type>
			<script task="createdb">
				<path>f7403t7403/createdb.script</path>
			</script>
			<script task="prepupdate">
				<path>f7403t7403/prepupdate.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
			<script task="prepuninst">
				<path>f7403t7403/prepuninst.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
		</database>
	</testrow>
	<testrow> <!-- 7.4.03 auf 7.5.00 -->
		<version role="source-start"><versionnumber>7.4.03.07</versionnumber></version>
		<version role="source-end"><versionnumber>7.4.03.31</versionnumber></version>
		<version role="target"><versionnumber state="DEV">7.5.00</versionnumber></version>
		<version role="brick"><versionnumber>7.5.00.02</versionnumber></version>
		<instprofile>Server</instprofile>
		<database>
			<type>OLTP</type>
			<script task="createdb">
				<path>f7403t7403/createdb.script</path>
			</script>
			<script task="prepupdate">
				<path>f7403t7403/prepupdate.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
			<script task="prepuninst">
				<path>f7403t7403/prepuninst.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
		</database>
	</testrow>
	<testrow> <!-- 7.5.00 auf 7.5.00 -->
		<version role="source-start"><versionnumber>7.5.00.03</versionnumber></version>
		<version role="source-end"><versionnumber>7.5.00.11</versionnumber></version>
		<version role="target"><versionnumber state="DEV">7.5.00</versionnumber></version>
		<version role="brick"><versionnumber>7.5.00.02</versionnumber></version>
		<instprofile>Server</instprofile>
		<database>
			<type>OLTP</type>
			<script task="createdb">
				<path>f7500t7500/createdb.script</path>
			</script>
			<script task="prepupdate">
				<path>f7500t7500/prepupdate.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
			<script task="prepuninst">
				<path>f7500t7500/prepuninst.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
		</database>
	</testrow>
</testrun>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/upgradetest/UpgradeTest/tests/unix_singletest.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE testrun SYSTEM "../testrun.dtd">
<testrun description="UpgradeTest">
	<environment>
		<os> </os>
		<bit> </bit>
		<platform> </platform>
	</environment>
	<test>
		<version role="source"><versionnumber>7.4.03.24</versionnumber></version>
		<version role="target"><versionnumber state="DEV">7.5.00</versionnumber></version>
		<instprofile>Server</instprofile>
		<updateNewSecurityConceptBackup/>
		<database>
			<type>OLTP</type>
			<script task="createdb">
				<path>scripts/createdb_74.script</path>
			</script>
			<script task="prepupdate">
				<path>scripts/nothing.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
			<script task="prepuninst">
				<path>scripts/dbdrop.script</path>
				<dbm>
					<property name="dbname" value="TESTDB"/>
				</dbm>
			</script>
		</database>
		<stop after="updateDB" when="failed" method="hold"/>
	</test>
</testrun>
