<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE deploy-manager-config [
<!ELEMENT deploy-manager-config (version-id, project-dir?, deployable-object, element*, login-info, user-role-mapping?, server-components-xml?, library-info?, supports, deployment-properties?, repl-var-properties?, log-file?)>
<!ELEMENT version-id (#PCDATA)>
<!ELEMENT project-dir (#PCDATA)>
<!ELEMENT deployable-object (ear-file|j2ee-module)>
<!ATTLIST deployable-object action-type (deploy|update) #REQUIRED>
<!ELEMENT ear-file (ear-path, display-name?, altdd*)>
<!ELEMENT ear-path (#PCDATA)>
<!ELEMENT display-name (#PCDATA)>
<!ELEMENT j2ee-module (archive-path, altdd*)>
<!ELEMENT archive-path (#PCDATA)>
<!ATTLIST j2ee-module container (appclient|connector|EJB_Container|servlet_jsp) #REQUIRED>
<!ELEMENT element (entry-name, context-root?, altdd*)>
<!ELEMENT context-root (#PCDATA)>
<!ELEMENT altdd (pathname, entry-name)>
<!ATTLIST altdd use-alternative (yes|no) #REQUIRED>
<!ELEMENT pathname (#PCDATA)>
<!ELEMENT entry-name (#PCDATA)>
<!ELEMENT login-info (host, port, transport-protocol*, user-name, user-password)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT transport-protocol (#PCDATA)>
<!ELEMENT user-name (#PCDATA)>
<!ELEMENT user-password (#PCDATA|psw-file)*>
<!ELEMENT psw-file (#PCDATA)>
<!ELEMENT user-role-mapping (role-name+)>
<!ELEMENT role-name (#PCDATA | mapping)*>
<!ELEMENT mapping (name, type)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT server-components-xml (#PCDATA)>
<!ELEMENT library-info (library*, reference*)>
<!ELEMENT library (lib-name, lib-jar+)>
<!ELEMENT lib-name (#PCDATA)>
<!ELEMENT lib-jar (#PCDATA)>
<!ATTLIST lib-jar server-map-name CDATA #REQUIRED>
<!ELEMENT reference (from-loader, to-loader+)>
<!ELEMENT from-loader (#PCDATA)>
<!ELEMENT to-loader (#PCDATA)>
<!ELEMENT supports (support+)>
<!ELEMENT support (#PCDATA)>
<!ELEMENT repl-var-properties (property*)>
<!ELEMENT deployment-properties (property*)>
<!ELEMENT property (#PCDATA)>
<!ELEMENT log-file (#PCDATA)>
]>

 

  <deploy-manager-config>

    <version-id></version-id>

    <project-dir>

      Your directory where MaxDB WebDAV Servlet was installed to <instdir>/servlets/webdav

    </project-dir>

    <deployable-object action-type="deploy">

      <ear-file>

        <ear-path>

          \webdavServletMaxDB-1.1.ear

        </ear-path>
        
        <display-name>
        
          MaxDB WebDAV
          
        </display-name>

        <altdd use-alternative="no">

        </altdd>

      </ear-file>

    </deployable-object>

    <login-info>

      <host>

        your SAP NetWeaver host

      </host>

      <port>

        your SAP NetWeaver p4 port (default 50004)

      </port>

      <transport-protocol>

        None

      </transport-protocol>

      <user-name>

        Your SAP NetWeaver Administrator

      </user-name>

      <user-password>

        Your SAP NetWeaver Administrator Pasword

      </user-password>

    </login-info>

    <user-role-mapping>

      <role-name>

        unknown role

      </role-name>

    </user-role-mapping>

    <library-info>

    </library-info>

    <supports>

      <support>

        p4

      </support>

    </supports>

    <deployment-properties>

      <property>

        container_type = B

      </property>

    </deployment-properties>

    <repl-var-properties>

    </repl-var-properties>

    <log-file>

      \deployer_log.txt

    </log-file>

  </deploy-manager-config>
