=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/sequencedescription.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--Root element-->
<!ELEMENT statements (execute | executeUpdate | sync | check | cleanUp )*>

<!--different statements-->

<!ELEMENT execute EMPTY >
<!ATTLIST execute statement CDATA #REQUIRED >
<!ATTLIST execute error     CDATA #IMPLIED  >

<!ELEMENT executeUpdate EMPTY >
<!ATTLIST executeUpdate statement CDATA #REQUIRED >
<!ATTLIST executeUpdate error     CDATA #IMPLIED  >
<!ATTLIST executeUpdate rowCount  CDATA #REQUIRED >

<!ELEMENT sync EMPTY >

<!ELEMENT check EMPTY >
<!ATTLIST check select CDATA #REQUIRED >
<!ATTLIST check result CDATA #REQUIRED >

<!ELEMENT cleanUp EMPTY >
<!ATTLIST cleanUp statement CDATA #REQUIRED >

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionSchema6user1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<execute statement="create schema [USER]S2"/>
	<execute statement="rollback"/>

	<execute statement="inner transaction begin"/>
	<execute statement="create table [USER]S2.TAB (ID integer primary key, NAME char(20))" error="-4030"/>
	<execute statement="insert [USER]S2.TAB values (1,'n1')" error="-4004"/>
	<execute statement="inner transaction rollback"/>

	<execute statement="select * from [USER]S2.TAB" error="-4004"/>

	<execute statement="commit"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionMisc14user1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<execute statement="create table TAB (ID integer primary key,NAME char(20))"/>

	<execute statement="commit"/>

	<execute statement="inner transaction begin"/>

	<execute statement="insert TAB values(1,'n1')"/>
	<execute statement="insert TAB values(2,'n2')"/>

	<execute statement="insert TAB values(3,'n3') with commit"/>
	<execute statement="insert TAB values(4,'n4') with commit"/>

	<execute statement="insert TAB values(5,'n5')"/>
	<execute statement="insert TAB values(6,'n6')"/>

	<execute statement="inner transaction commit"/>

	<execute statement="insert TAB values(7,'n7')"/>
	<execute statement="insert TAB values(8,'n8')"/>

	<execute statement="commit"/>	

	<check select="select * from TAB" result="([ID:integer, NAME:char]), (1,'n1'), (2,'n2'), (3,'n3'), (4,'n4'), (5,'n5'), (6,'n6'), (7,'n7'), (8,'n8')"/>

	<execute statement="commit"/>	

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionSynonym8user1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<execute statement="create table TAB (ID integer primary key, NAME char(20))"/>
	<execute statement="commit"/>
	<execute statement="create synonym BATMAN for TAB"/>
	<execute statement="rollback"/>

	<execute statement="inner transaction begin"/>
	<execute statement="insert BATMAN values(1,'Mueller')" error="-4004"/>
	<execute statement="insert TAB values(1,'Mueller')"/>
	<execute statement="inner transaction rollback"/>

	<execute statement="insert TAB values(2,'Mueller')"/>

	<check select="select * from TAB" result="([ID:integer, NAME:char]), (2,'Mueller')"/>
	<execute statement="select * from BATMAN" error="-4004"/>

	<execute statement="commit"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionUser5cleanUp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<cleanUp statement="drop user BUGSBUNNY1"/>
	<cleanUp statement="drop user BUGSBUNNY2"/>
	<cleanUp statement="drop user BUGSBUNNY3"/>
	<cleanUp statement="drop user BUGSBUNNY4"/>
	<cleanUp statement="drop user BUGSBUNNY5"/>
	<cleanUp statement="drop user BBUGSBUNNY6"/>

	<cleanUp statement="drop user COYOTE5"/>
	<cleanUp statement="drop user COYOTE6"/>

	<cleanUp statement="commit"/>	

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionTable32user1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<execute statement="create table TAB (ID integer primary key,NAME char(20))"/>

	<execute statement="inner transaction begin"/>
	<execute statement="rename table TAB to BAT" error="500"/>
	<execute statement="inner transaction rollback"/>

	<execute statement="insert BAT values(1,'n1')" error="-4004"/>

	<execute statement="insert TAB values(2,'n2')"/>

	<check select="select * from TAB" result="([ID:integer,NAME:char]),(2,'n2')"/>
	<execute statement="commit"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionGrant6user1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<!-- test -->
	<execute statement="create usergroup MOPPELPOPPEL11"/>
	<execute statement="rollback"/>

	<execute statement="inner transaction begin"/>
	<execute statement="grant usergroup MOPPELPOPPEL11 TO PETERUWE12" error="-4013"/>
	<execute statement="inner transaction rollback"/>

	<sync/>

	<execute statement="drop usergroup MOPPELPOPPEL12" error="-4013"/>
	<execute statement="commit"/>

	<!-- cleanUp -->
	<cleanUp statement="drop usergroup MOPPELPOPPEL11"/>
	<cleanUp statement="commit"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionTable15user1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<execute statement="create table TAB (ID integer primary key,NAME char(20) default 'Hansi')"/>
	<execute statement="commit"/>

	<execute statement="inner transaction begin"/>
	<execute statement="rename column TAB.ID to NUMBER"/>
	<execute statement="inner transaction commit"/>

	<execute statement="insert TAB (NUMBER) values(1)"/>

	<execute statement="insert TAB (ID) values(1)" error="-4005"/>

	<check select="select * from TAB" result="([NUMBER:integer, NAME:char]),(1,'Hansi')"/>
	<execute statement="commit"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionRole9user1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<!-- prepare -->
	<execute statement="create user [USER]Z1 password PUPS"/>
	<execute statement="create role [USER]Z"/>

	<!-- test -->
	<execute statement="inner transaction begin"/>
	<execute statement="grant [USER]Z to [USER]Z1" error="500"/>
	<execute statement="inner transaction commit"/>

	<execute statement="commit"/>

	<!-- clean up -->	
	<cleanUp statement="commit"/>
	<cleanUp statement="drop user [USER]Z1"/>
	<cleanUp statement="drop role [USER]Z"/>
	<cleanUp statement="commit"/>

</statements>
