=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/sequencedescription.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--Root element-->
<!ELEMENT statements (execute | executeUpdate | sync | check | cleanUp )*>

<!--different statements-->

<!ELEMENT execute EMPTY >
<!ATTLIST execute statement CDATA #REQUIRED >
<!ATTLIST execute error     CDATA #IMPLIED  >

<!ELEMENT executeUpdate EMPTY >
<!ATTLIST executeUpdate statement CDATA #REQUIRED >
<!ATTLIST executeUpdate error     CDATA #IMPLIED  >
<!ATTLIST executeUpdate rowCount  CDATA #REQUIRED >

<!ELEMENT sync EMPTY >

<!ELEMENT check EMPTY >
<!ATTLIST check select CDATA #REQUIRED >
<!ATTLIST check result CDATA #REQUIRED >

<!ELEMENT cleanUp EMPTY >
<!ATTLIST cleanUp statement CDATA #REQUIRED >

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionUser4cleanUp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<cleanUp statement="drop user BIENEMAJA1"/>
	<cleanUp statement="drop user BIENEMAJA2"/>
	<cleanUp statement="drop user BIENEMAJA3"/>
	<cleanUp statement="drop user BIENEMAJA4"/>
	<cleanUp statement="drop user BIENEMAJA5"/>
	<cleanUp statement="drop user BIENEMAJA6"/>


	<cleanUp statement="drop user WILLI1"/>
	<cleanUp statement="drop user WILLI2"/>
	<cleanUp statement="drop user WILLI3"/>
	<cleanUp statement="drop user WILLI4"/>
	<cleanUp statement="drop user WILLI5"/>
	<cleanUp statement="drop user WILLI6"/>

	<cleanUp statement="commit"/>	

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionDomain4user1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>
	<execute statement="create domain SURNAME char(20) default 'Meier'"/>
	<execute statement="commit"/>

	<execute statement="inner transaction begin"/>
	<execute statement="create table TAB (ID integer primary key, NAME SURNAME)"/>
	<execute statement="inner transaction rollback"/>

	<execute statement="insert TAB values (1,'Mueller')" error="-4004"/>
	<execute statement="commit"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionIndex11user1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<execute statement="create table TAB (ID integer primary key, NAME char(20), SURNAME char(20))"/>
	<execute statement="commit"/>
	<execute statement="create unique index NAME_INDEX on TAB (NAME ASC, SURNAME DESC)"/>
	<execute statement="rollback"/>

	<execute statement="inner transaction begin"/>
	<execute statement="rename index NAME_INDEX on TAB to INDEX_NAME" error="-4011"/>
	<execute statement="inner transaction commit"/>

	<check select="select * from DOMAIN.INDEXES where SCHEMANAME = '[USER]' AND OWNER = '[USER]' AND TABLENAME = 'TAB' AND INDEXNAME = 'INDEX_NAME'" result="0"/>
	<check select="select * from DOMAIN.INDEXES where SCHEMANAME = '[USER]' AND OWNER = '[USER]' AND TABLENAME = 'TAB' AND INDEXNAME = 'NAME_INDEX'" result="0"/>
	
	<execute statement="commit"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionSynonym9user1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<execute statement="create table TAB (ID integer primary key, NAME char(20))"/>
	<execute statement="create synonym BATMAN for TAB"/>
	<execute statement="commit"/>

	<execute statement="inner transaction begin"/>
	<execute statement="drop synonym BATMAN"/>
	<execute statement="inner transaction commit"/>

	<execute statement="insert BATMAN values(1,'Mueller')" error="-4004"/>
	<execute statement="insert TAB values(1,'Mueller')"/>

	<check select="select * from TAB" result="([ID:integer, NAME:char]),(1,'Mueller')"/>

	<execute statement="commit"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionSchema4user1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<execute statement="create schema [USER]S2"/>
	<execute statement="commit"/>

	<execute statement="inner transaction begin"/>
	<execute statement="create table [USER]S2.TAB (ID integer primary key, NAME char(20))"/>
	<execute statement="insert [USER]S2.TAB values (1,'n1')"/>
	<execute statement="insert [USER]S2.TAB values (2,'n2')"/>
	<execute statement="inner transaction rollback"/>

	<execute statement="select * from [USER]S2.TAB" error="-4004"/>

	<execute statement="commit"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionGrant21user2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<!-- test -->
	<execute statement="create schema MOPPELPOPPEL42"/>
	<execute statement="commit"/>
	<execute statement="grant createin on MOPPELPOPPEL42 TO PETERUWE41"/>
	<execute statement="rollback"/>

	<execute statement="inner transaction begin"/>
	<execute statement="revoke createin on MOPPELPOPPEL42 from PETERUWE41"/>
	<execute statement="inner transaction commit"/>

	<sync/>

	<execute statement="create table MOPPELPOPPEL41.TAB (ID integer primary key, NAME char(20))" error="-5001"/>
	<execute statement="commit"/>

	<!-- cleanUp -->
	<cleanUp statement="drop schema MOPPELPOPPEL42"/>
	<cleanUp statement="commit"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionUsergroup13cleanUp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<cleanUp statement="drop user HACKBERT1"/>
	<cleanUp statement="drop user HACKBERT2"/>
	<cleanUp statement="drop user HACKBERT3"/>
	<cleanUp statement="drop user HACKBERT4"/>

	<cleanUp statement="drop usergroup KINDERGARTEN1"/>
	<cleanUp statement="drop usergroup KINDERGARTEN2"/>
	<cleanUp statement="drop usergroup KINDERGARTEN3"/>
	<cleanUp statement="drop usergroup KINDERGARTEN4"/>

	<cleanUp statement="commit"/>	

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionGrant3user2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<!-- test -->
	<execute statement="create user MOPPELPOPPEL6 password PUPS standard"/>
	<execute statement="rollback"/>

	<execute statement="inner transaction begin"/>
	<execute statement="grant user MOPPELPOPPEL6 TO PETERUWE5" error="-4003"/>
	<execute statement="inner transaction commit"/>

	<sync/>

	<execute statement="drop user MOPPELPOPPEL5" error="-4003"/>
	<execute statement="commit"/>

	<!-- cleanUp -->
	<cleanUp statement="drop user MOPPELPOPPEL6"/>
	<cleanUp statement="commit"/>

</statements>
