=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/sequencedescription.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--Root element-->
<!ELEMENT statements (execute | executeUpdate | sync | check | cleanUp )*>

<!--different statements-->

<!ELEMENT execute EMPTY >
<!ATTLIST execute statement CDATA #REQUIRED >
<!ATTLIST execute error     CDATA #IMPLIED  >

<!ELEMENT executeUpdate EMPTY >
<!ATTLIST executeUpdate statement CDATA #REQUIRED >
<!ATTLIST executeUpdate error     CDATA #IMPLIED  >
<!ATTLIST executeUpdate rowCount  CDATA #REQUIRED >

<!ELEMENT sync EMPTY >

<!ELEMENT check EMPTY >
<!ATTLIST check select CDATA #REQUIRED >
<!ATTLIST check result CDATA #REQUIRED >

<!ELEMENT cleanUp EMPTY >
<!ATTLIST cleanUp statement CDATA #REQUIRED >

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionUsergroup8user1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<!-- test -->
	<execute statement="create usergroup [USER]UG"/>
	<execute statement="rollback"/>

	<execute statement="inner transaction begin"/>
	<execute statement="drop usergroup [USER]UG" error="-4013"/>
	<execute statement="inner transaction rollback"/>

	<execute statement="create user [USER]UG1 password PUPS usergroup [USER]UG" error="-4013"/>
	<execute statement="commit"/>

	<!-- clean up -->	
	<cleanUp statement="drop user [USER]UG1"/>
	<cleanUp statement="drop usergroup [USER]UG"/>
	<cleanUp statement="commit"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionUsergroup13user4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<!-- test -->
	<execute statement="create usergroup KINDERGARTEN3 RESOURCE"/>
	<execute statement="rollback"/>

	<execute statement="inner transaction begin"/>
	<execute statement="alter usergroup KINDERGARTEN3 STANDARD" error="-4013"/>
	<execute statement="inner transaction rollback"/>

	<execute statement="create user HACKBERT3 password PUPS usergroup KINDERGARTEN3" error="-4013"/>
	<execute statement="commit"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionGrant15user2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<!-- test -->
	<execute statement="create sequence MOPPELPOPPEL30 increment by 2 start with 3"/>
	<execute statement="rollback"/>

	<execute statement="inner transaction begin"/>
	<execute statement="grant select on MOPPELPOPPEL30 TO PETERUWE29" error="-4004"/>
	<execute statement="inner transaction commit"/>

	<sync/>

	<execute statement="create table TAB(ID integer primary key, NAME char(20))"/>
	<execute statement="insert TAB values (PETERUWE29.MOPPELPOPPEL29.nextval,'name')" error="-4020"/>
	
	<execute statement="commit"/>

	<!-- cleanUp -->
	<cleanUp statement="drop sequence MOPPELPOPPEL30"/>
	<cleanUp statement="commit"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionGrant14user2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<!-- test -->
	<execute statement="create sequence MOPPELPOPPEL28 increment by 2 start with 3"/>
	<execute statement="commit"/>

	<execute statement="inner transaction begin"/>
	<execute statement="grant select on MOPPELPOPPEL28 TO PETERUWE27"/>
	<execute statement="inner transaction rollback"/>

	<sync/>

	<execute statement="create table TAB(ID integer primary key, NAME char(20))"/>
	<execute statement="insert TAB values (PETERUWE27.MOPPELPOPPEL27.nextval,'name')" error="-4020"/>
	
	<execute statement="commit"/>

	<!-- cleanUp -->
	<cleanUp statement="drop sequence MOPPELPOPPEL28"/>
	<cleanUp statement="commit"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionGrant12user1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<!-- test -->
	<execute statement="create schema MOPPELPOPPEL23"/>
	<execute statement="rollback"/>

	<execute statement="inner transaction begin"/>
	<execute statement="grant createin on MOPPELPOPPEL23 TO PETERUWE24" error="-4030"/>
	<execute statement="inner transaction commit"/>

	<sync/>

	<execute statement="create table MOPPELPOPPEL24.TAB (ID integer primary key, NAME char(20))" error="-4030"/>
	<execute statement="commit"/>

	<!-- cleanUp -->
	<cleanUp statement="drop schema MOPPELPOPPEL23"/>
	<cleanUp statement="commit"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionMisc8user1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<execute statement="create table TAB1 (ID integer primary key,NAME char(20))"/>

	<execute statement="inner transaction rollback" error="-7065"/>

	<execute statement="rename column TAB1.NAME to SURNAME"/>

	<execute statement="insert TAB1 values(1,'n1')"/>
	<execute statement="insert TAB1 values(2,'n2')"/>

	<check select="select * from TAB1" result="([ID:integer, SURNAME:char]), (1,'n1'), (2,'n2')"/>

	<execute statement="commit"/>	

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionGrant23user2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<!-- test -->
	<execute statement="create sequence MOPPELPOPPEL46 increment by 2 start with 3"/>
	<execute statement="grant select on MOPPELPOPPEL46 TO PETERUWE45"/>
	<execute statement="commit"/>

	<execute statement="inner transaction begin"/>
	<execute statement="revoke select on MOPPELPOPPEL46 from PETERUWE45"/>
	<execute statement="inner transaction rollback"/>

	<sync/>

	<execute statement="create table TAB(ID integer primary key, NAME char(20))"/>
	<execute statement="insert TAB values (PETERUWE45.MOPPELPOPPEL45.nextval,'name')"/>
	<execute statement="insert TAB values (1,'name')"/>

	<check select="select * from TAB" result="([ID:integer, NAME:char]), (1,'name'), (3,'name')"/>
	<execute statement="commit"/>

	<!-- cleanUp -->
	<cleanUp statement="drop sequence MOPPELPOPPEL46"/>
	<cleanUp statement="commit"/>

</statements>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionUser3user5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statements SYSTEM "sequencedescription.dtd">
<statements>

	<execute statement="commit"/>
	<execute statement="create user YOGIBAER5 password PUPS resource"/>
	<execute statement="rollback"/>

	<execute statement="inner transaction begin"/>
	<execute statement="alter user YOGIBAER5 standard" error="-4003"/>

	<execute statement="inner transaction commit"/>	
	<execute statement="commit"/>	

</statements>
