=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/testdescription.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--Root element-->
<!ELEMENT test (db*,tryToConnect*,thread*)>

<!ELEMENT tryToConnect EMPTY >
<!ATTLIST tryToConnect userName    CDATA #REQUIRED >
<!ATTLIST tryToConnect password    CDATA #REQUIRED >
<!ATTLIST tryToConnect expectError CDATA #REQUIRED >

<!ELEMENT db EMPTY >
<!ATTLIST db parameter CDATA #REQUIRED >
<!ATTLIST db value     CDATA #REQUIRED >

<!ELEMENT thread EMPTY >
<!ATTLIST thread sequence CDATA #REQUIRED >
<!ATTLIST thread userName     CDATA #IMPLIED >
<!ATTLIST thread userType     CDATA #IMPLIED >
<!ATTLIST thread password     CDATA #IMPLIED >
<!ATTLIST thread number       CDATA #IMPLIED >
<!ATTLIST thread create       CDATA #IMPLIED >

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/innertransaction/InnerTransactionTest/innerTransactionUser4_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE test SYSTEM "testdescription.dtd">

<test>
	<tryToConnect userName="BIENEMAJA1" password="PUPS" expectError="TRUE"/>
	<tryToConnect userName="BIENEMAJA2" password="PUPS" expectError="FALSE"/>
	<tryToConnect userName="BIENEMAJA3" password="PUPS" expectError="TRUE"/>
	<tryToConnect userName="BIENEMAJA4" password="PUPS" expectError="FALSE"/>
	<tryToConnect userName="BIENEMAJA5" password="PUPS" expectError="TRUE"/>
	<tryToConnect userName="BIENEMAJA6" password="PUPS" expectError="TRUE"/>

	<tryToConnect userName="WILLI1" password="PUPS" expectError="FALSE"/>
	<tryToConnect userName="WILLI2" password="PUPS" expectError="TRUE"/>
	<tryToConnect userName="WILLI3" password="PUPS" expectError="FALSE"/>
	<tryToConnect userName="WILLI4" password="PUPS" expectError="TRUE"/>
	<tryToConnect userName="WILLI5" password="PUPS" expectError="TRUE"/>
	<tryToConnect userName="WILLI6" password="PUPS" expectError="TRUE"/>


	<thread sequence = "innerTransactionUser4cleanUp.xml" userName="UWEHEINZ4" create="FALSE"/>

</test>
