=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/loader/LoaderTestInterpreter/SQLReferenceCatalog.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--Root element of the catalog-->
<!ELEMENT CATALOG (LEVEL+)>
<!ATTLIST CATALOG
	Comment CDATA #IMPLIED
>
<!--Definition of a level of the catalog-->
<!ELEMENT LEVEL (LEVEL*, REFERENCE*)>
<!ATTLIST LEVEL
	Name CDATA #REQUIRED
	Comment CDATA #IMPLIED
	Status (planned | inprogress | finished) #IMPLIED
>
<!--Definition of a link to a test case-->
<!ELEMENT REFERENCE EMPTY>
<!ATTLIST REFERENCE
	Number CDATA #REQUIRED
	FileName CDATA #REQUIRED
	selected (true | false) "false"
>

=== GunterMueller/MaxDB_GPL_Releases/7.6.00.37/V76_00_37/MaxDB_ORG/sys/src/jtest/tests/input/interpreter/TestCasesInterpreter/DbprocCatalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CATALOG SYSTEM "SQLReferenceCatalog.dtd">
<CATALOG Comment="">
<LEVEL Name="Data Definition Language">
<LEVEL Name="CREATE db_proc">
<LEVEL Name="datatypes">
<REFERENCE FileName="dbProcTests.xml" Number="7" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="18" selected="true"/>
</LEVEL>
<LEVEL Name="procedure_name">
<REFERENCE FileName="dbProcTests.xml" Number="3" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="10" selected="true"/>
</LEVEL>
<LEVEL Name="RETURNS CURSOR">
<REFERENCE FileName="dbProcTests.xml" Number="6" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="555" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="1350" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="277" selected="true"/>
</LEVEL>
<LEVEL Name="statement">
<LEVEL Name="routine_sql_statement">
<REFERENCE FileName="dbProcTests.xml" Number="11" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="12" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="13" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="14" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="15" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="19" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="20" selected="true"/>
</LEVEL>
<LEVEL Name="case_statement">
<REFERENCE FileName="dbProcTests.xml" Number="4" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="5" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="17" selected="true"/>
</LEVEL>
<LEVEL Name="CursorWithRecursive_statement">
<REFERENCE FileName="dbProcTests.xml" Number="552" selected="true"/>
</LEVEL>
</LEVEL>
<REFERENCE FileName="dbProcTests.xml" Number="1" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="2" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="8" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="9" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="16" selected="true"/>
<REFERENCE FileName="dbProcTests.xml" Number="243" selected="true"/>
</LEVEL>
<LEVEL Name="DBPROC_TRIGGER_TESTS" Status="inprogress">
<REFERENCE FileName="DBPROC_TRIGGER.xml" Number="1" selected="true"/>
<REFERENCE FileName="DBPROC_TRIGGER.xml" Number="822" selected="true"/>
</LEVEL>
<LEVEL Name="FunctionTests">
<REFERENCE FileName="DBFuncTests.xml" Number="1" selected="false"/>
<REFERENCE FileName="DBFuncTests.xml" Number="686" selected="false"/>
<REFERENCE FileName="DBFuncTests.xml" Number="1404" selected="true"/>
<REFERENCE FileName="DBFuncTests.xml" Number="501" selected="false"/>
<REFERENCE FileName="DBFuncTests.xml" Number="404" selected="false"/>
</LEVEL>
<LEVEL Name="Bug fixes">
<REFERENCE FileName="dbProcTests.xml" Number="557" selected="false"/>
</LEVEL>
</LEVEL>
</CATALOG>
